sudo: true
language: erlang

# Choose which platforms you want your builds run against (done in parallel)
env:
   - ST=Squeak-4.5
   - ST=Squeak-Trunk

matrix:
   allow_failures:
   - env: ST=Squeak-Trunk

# Boilerplate ... should be no reason to edit the install section
install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O builderCI.zip https://github.com/dalehenrich/builderCI/archive/master.zip
   - unzip -q builderCI.zip
   - cd builderCI-*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

# use a different script if you want to customize how travis tests are run
# use verbose flag to dump transcript unconditionally
script: $BUILDER_CI_HOME/testTravisCI.sh # -verbose 